// Copyright (c) 2026 Varun Pratap Bhardwaj
// Part of Qualixar OS | https://qualixar.com | License: FSL-1.1-ALv2
/**
 * Qualixar OS -- Code Intelligence Ingester (Layer 2a)
 *
 * Production-grade code intelligence powered by code-review-graph.
 *
 * Architecture:
 * 1. code-review-graph builds AST-based knowledge graph (6K+ nodes, 57K+ edges)
 * 2. code-review-graph generates wiki pages (465 community pages)
 * 3. This module ingests wiki pages + key source extracts into the memory store
 * 4. Content-hash caching skips unchanged files on restart
 *
 * The wiki pages contain: class/function members with line numbers,
 * execution flows, incoming/outgoing dependencies, cohesion scores —
 * all extracted via tree-sitter AST, not regex.
 *
 * On every release: rebuild graph → regenerate wiki → re-ingest.
 * The help chatbot's knowledge stays current automatically.
 */

import { readFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, extname, relative } from 'node:path';
import type { DocumentIngester } from '../memory/document-ingester.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CodeIntelResult {
  readonly totalChunks: number;
  readonly wikiPages: number;
  readonly sourceExtracts: number;
  readonly categories: Record<string, number>;
  readonly errors: readonly string[];
  readonly cached: number;
}

export interface HashCache {
  readonly hashes: Map<string, string>;
}

// ---------------------------------------------------------------------------
// SHA-256 Content Hash
// ---------------------------------------------------------------------------

function computeHash(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

// ---------------------------------------------------------------------------
// Layer 2a-Primary: Wiki Page Ingestion
// ---------------------------------------------------------------------------

/**
 * Ingest code-review-graph wiki pages into the memory store.
 * Each wiki page covers a code community with:
 * - Members (classes, functions) with file paths and line numbers
 * - Execution flows with criticality scores
 * - Outgoing/incoming dependencies
 * - Cohesion metrics
 *
 * These are generated by tree-sitter AST analysis, not regex.
 */
async function ingestWikiPages(
  ingester: DocumentIngester,
  wikiDir: string,
  hashCache: HashCache,
): Promise<{ chunks: number; cached: number; errors: string[] }> {
  let chunks = 0;
  let cached = 0;
  const errors: string[] = [];

  let entries;
  try {
    entries = await readdir(wikiDir);
  } catch {
    return { chunks: 0, cached: 0, errors: [`Wiki directory not found: ${wikiDir}. Run code-review-graph build first.`] };
  }

  const mdFiles = entries.filter((e) => extname(e) === '.md' && e !== 'index.md');

  for (const file of mdFiles) {
    const filePath = join(wikiDir, file);
    try {
      const content = await readFile(filePath, 'utf-8');
      const hash = computeHash(content);

      if (hashCache.hashes.get(`wiki:${file}`) === hash) {
        cached++;
        continue;
      }

      // Extract community name from filename
      const communityName = file.replace('.md', '').replace(/-/g, ' ');

      await ingester.ingestContent(
        content,
        `Code Community: ${communityName}`,
        filePath,
        {
          chunkSize: 1500,
          chunkOverlap: 200,
          layer: 'semantic',
          metadata: {
            docType: 'code-intel',
            category: 'wiki-community',
            communityName,
            source: 'code-review-graph',
            generatedBy: 'tree-sitter-ast',
          },
        },
      );

      hashCache.hashes.set(`wiki:${file}`, hash);
      chunks++;
    } catch (err) {
      errors.push(`Wiki ${file}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return { chunks, cached, errors };
}

// ---------------------------------------------------------------------------
// Layer 2a-Secondary: Key Source Extracts
// ---------------------------------------------------------------------------

/**
 * Extract critical source knowledge that wiki pages may not fully cover:
 * - Event type catalog (all 203 event types grouped by phase)
 * - Provider type catalog (all supported LLM providers)
 * - API route catalog (all REST endpoints)
 * - Tool category definitions
 *
 * These are extracted via targeted parsing of known files.
 */
async function ingestSourceExtracts(
  ingester: DocumentIngester,
  projectRoot: string,
  hashCache: HashCache,
): Promise<{ chunks: number; cached: number; errors: string[] }> {
  let chunks = 0;
  let cached = 0;
  const errors: string[] = [];

  const extracts: { file: string; extractor: (src: string) => string | null; title: string; category: string }[] = [
    {
      file: 'src/types/events.ts',
      title: 'Complete Event Type Catalog',
      category: 'event-catalog',
      extractor: (src) => {
        const events = [...src.matchAll(/'([a-z_]+:[a-z_]+)'/g)].map((m) => m[1]);
        if (events.length === 0) return null;
        const grouped = new Map<string, string[]>();
        let phase = 'general';
        for (const line of src.split('\n')) {
          const cm = line.match(/\/\/\s*(.+?)(?:\s*--\s*\d+)?$/);
          if (cm && !line.includes("'")) phase = cm[1].trim();
          for (const m of line.matchAll(/'([a-z_]+:[a-z_]+)'/g)) {
            const g = grouped.get(phase) ?? [];
            g.push(m[1]);
            grouped.set(phase, g);
          }
        }
        const sections = [...grouped.entries()]
          .map(([p, evts]) => `### ${p}
${evts.map((e) => `- \`${e}\``).join('\n')}`)
          .join('\n\n');
        return `# Qualixar OS Event Type Catalog

Total: ${events.length} event types.
Subscribe: \`eventBus.on('event:name', handler)\`

${sections}`;
      },
    },
    {
      file: 'src/types/common.ts',
      title: 'Supported LLM Providers',
      category: 'provider-catalog',
      extractor: (src) => {
        const match = src.match(/z\.enum\(\[\s*([\s\S]*?)\]\)/);
        if (!match) return null;
        const providers = [...match[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
        const local = providers.filter((p) => ['ollama', 'lmstudio', 'llamacpp', 'vllm', 'huggingface-tgi'].includes(p));
        const cloud = providers.filter((p) => !local.includes(p) && p !== 'custom');
        return `# Qualixar OS LLM Provider Catalog

Total: ${providers.length} providers.

## Cloud Providers
${cloud.map((p) => `- \`${p}\``).join('\n')}

## Local Providers
${local.map((p) => `- \`${p}\``).join('\n')}

## Custom
- \`custom\` — Any OpenAI-compatible endpoint

Configure in \`~/.qualixar-os/config.yaml\` under \`providers:\`.
Local providers auto-detected on startup (Ollama:11434, LM Studio:1234, vLLM:8000, llama.cpp:8080).`;
      },
    },
    {
      file: 'src/tools/tool-categories.ts',
      title: 'Tool Category System',
      category: 'tool-catalog',
      extractor: (src) => {
        const cats = [...src.matchAll(/\{\s*id:\s*'([^']+)',\s*label:\s*'([^']+)',\s*description:\s*'([^']+)'/g)]
          .map((m) => ({ id: m[1], label: m[2], desc: m[3] }));
        if (cats.length === 0) return null;
        return `# Qualixar OS Tool Categories

${cats.length} categories for automatic tool selection.

${cats.map((c) => `## ${c.label} (\`${c.id}\`)
${c.desc}`).join('\n\n')}

Forge auto-selects categories based on task type. Tools are categorized via pattern matching on name + description.`;
      },
    },
  ];

  // Also extract all API routes from route files
  const routeFiles = [
    'src/channels/http-server.ts',
    'src/help/help-routes.ts',
    'src/marketplace/marketplace-routes.ts',
    'src/enterprise/enterprise-routes.ts',
    'src/builder/workflow-routes.ts',
  ];

  const allRoutes: string[] = [];
  for (const rf of routeFiles) {
    try {
      const src = await readFile(join(projectRoot, rf), 'utf-8');
      for (const m of src.matchAll(/app\.(get|post|put|delete)\('(\/api\/[^']+)'/g)) {
        allRoutes.push(`${m[1].toUpperCase()} ${m[2]}`);
      }
    } catch { /* file may not exist */ }
  }

  if (allRoutes.length > 0) {
    extracts.push({
      file: '_generated_routes',
      title: 'Complete REST API Reference',
      category: 'api-catalog',
      extractor: () => {
        const grouped = new Map<string, string[]>();
        for (const route of allRoutes) {
          const domain = route.split('/')[2] ?? 'other';
          const g = grouped.get(domain) ?? [];
          g.push(route);
          grouped.set(domain, g);
        }
        const sections = [...grouped.entries()]
          .map(([d, routes]) => `## /api/${d}
${routes.map((r) => `- \`${r}\``).join('\n')}`)
          .join('\n\n');
        return `# Qualixar OS REST API Reference

Base URL: http://localhost:${process.env.QOS_PORT ?? process.env.PORT ?? '3000'}
Total: ${allRoutes.length} endpoints.

${sections}`;
      },
    });
  }

  for (const extract of extracts) {
    try {
      let content: string | null;
      if (extract.file === '_generated_routes') {
        content = extract.extractor('');
      } else {
        const src = await readFile(join(projectRoot, extract.file), 'utf-8');
        const hash = computeHash(src);
        if (hashCache.hashes.get(`extract:${extract.file}`) === hash) {
          cached++;
          continue;
        }
        content = extract.extractor(src);
        hashCache.hashes.set(`extract:${extract.file}`, hash);
      }

      if (content) {
        await ingester.ingestContent(content, extract.title, extract.file, {
          chunkSize: 2000,
          chunkOverlap: 200,
          layer: 'semantic',
          metadata: {
            docType: 'code-intel',
            category: extract.category,
            title: extract.title,
            source: 'qualixar-source-extract',
          },
        });
        chunks++;
      }
    } catch (err) {
      errors.push(`Extract ${extract.title}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return { chunks, cached, errors };
}

// ---------------------------------------------------------------------------
// Main Ingestion
// ---------------------------------------------------------------------------

/**
 * Ingest code intelligence from two sources:
 * 1. Wiki pages generated by code-review-graph (primary — AST-based)
 * 2. Key source extracts (secondary — targeted parsing of known files)
 *
 * Uses SHA-256 content-hash caching to skip unchanged files on restart.
 *
 * Call flow on every release:
 *   code-review-graph build → code-review-graph wiki → ingestCodeIntel()
 */
export async function ingestCodeIntel(
  ingester: DocumentIngester,
  projectRoot: string,
  hashCache?: HashCache,
): Promise<CodeIntelResult> {
  const cache = hashCache ?? createHashCache();
  const categories: Record<string, number> = {};
  const allErrors: string[] = [];
  let totalCached = 0;

  // 1. Ingest wiki pages (primary — 465 community pages from tree-sitter AST)
  const wikiDir = join(projectRoot, '.code-review-graph', 'wiki');
  const wiki = await ingestWikiPages(ingester, wikiDir, cache);
  categories['wiki-community'] = wiki.chunks;
  totalCached += wiki.cached;
  allErrors.push(...wiki.errors);

  // 2. Ingest key source extracts (secondary — event catalog, provider catalog, etc.)
  const extracts = await ingestSourceExtracts(ingester, projectRoot, cache);
  categories['source-extracts'] = extracts.chunks;
  totalCached += extracts.cached;
  allErrors.push(...extracts.errors);

  return {
    totalChunks: wiki.chunks + extracts.chunks,
    wikiPages: wiki.chunks,
    sourceExtracts: extracts.chunks,
    categories,
    errors: allErrors,
    cached: totalCached,
  };
}

/**
 * Create a hash cache for content-hash based re-ingestion skipping.
 */
export function createHashCache(): HashCache {
  return { hashes: new Map() };
}
